language: generic

sudo: required

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "sample-go-app"
  env: "SampleGoApp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-169835060998"
  bucket_path: "sample-go-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
